### YamlMime:Lifecycle
metadata:
  title: Bộ quản lý Cấu hình Microsoft System Center 2007 R3
  description: Trình quản lý Cấu hình Hệ thống Trung tâm Microsoft 2007 R3 tuân theo Chính sách Vòng đời Cố định.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1066e1999c057459643c64aba46bb88e34bb4842
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4137444"
name: Bộ quản lý Cấu hình Microsoft System Center 2007 R3
summary: >
  Trình quản lý Cấu hình Hệ thống Trung tâm của Microsoft 2007 R3 tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > Hỗ trợ dành cho sản phẩm này đã kết thúc Xem hướng dẫn di chuyển bên dưới.
products:
- msc
policyType: fixed
supportDates:
  start: 2010-12-19T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2010-12-19T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Liên kết \n* [Hướng dẫn di chuyển](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Hướng dẫn chuyển đổi bổ sung](/mem/configmgr/core/migration/planning-for-migration)"
