### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security theo chính sách vòng đời cố định.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924278"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security theo chính sách vòng đời [cố định](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Liên kết \n* [Bảo vệ điểm cuối Trung tâm hệ thống](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security đã ngừng hoạt động từ ngày 14 tháng 7 năm 2015. Các bản cập nhật định nghĩa antimalware và Antispyware sẽ không còn sẵn dùng sau khi kết thúc hỗ trợ cho phiên bản sản phẩm. Vui lòng đánh giá bảo vệ điểm cuối Trung tâm hệ thống như một thay thế."
