### YamlMime:Lifecycle
metadata:
  title: Bộ quản lý Cấu hình Microsoft System Center 2007
  description: Microsoft System Center Configuration Manager 2007 tuân theo Chính sách Vòng đời Cố định.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1b1f1b01df25eb733d93d618831fa157855d5318
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4144141"
name: Bộ quản lý Cấu hình Microsoft System Center 2007
summary: >
  Microsoft System Center Configuration Manager 2007 tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > Hỗ trợ dành cho sản phẩm này đã kết thúc Xem hướng dẫn di chuyển bên dưới.
products:
- msc
policyType: fixed
supportDates:
  start: 2007-11-29T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2009-10-22T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2008-05-21T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2007-11-29T00:00:00.000-08:00
  endDate: 2009-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Liên kết \n* [Hướng dẫn di chuyển](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Thông tin sản phẩm](/mem/configmgr/core/understand/introduction)\n* [Chính sách gói dịch vụ](/lifecycle/policies/fixed#service-packs)"
