### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.5 dành cho Máy tính để bàn Windows
  description: Microsoft Application Virtualization Hosting 4.5 cho Windows Desktops tuân theo Chính sách Vòng đời Cố định.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 2e50dff8c1e7f1db82d46a06704bad1c76d16598
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4154057"
name: Microsoft Application Virtualization Hosting 4.5 dành cho Máy tính để bàn Windows
summary: >
  Microsoft Application Virtualization Hosting 4.5 cho Windows Desktops tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/fixed).


  Chính sách này áp dụng cho các phiên bản sau: cho Windows Desktops


  > [!IMPORTANT]

  > Hỗ trợ dành cho sản phẩm này đã kết thúc Xem thông tin di chuyển bên dưới.
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Liên kết \n* [Thông tin sản phẩm và di chuyển](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Chính sách gói dịch vụ](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Phiên bản \n* cho Windows Desktops"
