### YamlMime:Lifecycle
metadata:
  title: Bộ quản lý Cấu hình Microsoft System Center 2007 R2
  description: Trình quản lý Cấu hình Hệ thống Trung tâm Microsoft 2007 R2 tuân theo Chính sách Vòng đời Cố định.
  ms.date: 07/28/2020
  ms.openlocfilehash: d74ead7a94de9a66a4f34abab6d8ff9b4496c86479bf1242d36b903855a6e66f
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511300"
name: Bộ quản lý Cấu hình Microsoft System Center 2007 R2
summary: >
  Trình quản lý Cấu hình Hệ thống Trung tâm Microsoft 2007 R2 tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > Hỗ trợ dành cho sản phẩm này đã kết thúc Xem hướng dẫn di chuyển bên dưới.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Liên kết \n* [Hướng dẫn di chuyển](/mem/configmgr/core/migration/planning-for-migration)\n* [Hướng dẫn chuyển đổi bổ sung](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
