### YamlMime:Lifecycle
metadata:
  title: Quản lý cấu hình Microsoft System Center 2007
  description: Microsoft System Center Configuration Manager 2007 tuân theo chính sách vòng đời cố định.
  ms.date: 07/28/2020
  ms.openlocfilehash: 796670fd93547cc79f69c544085070efb0116650
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "846949"
name: Quản lý cấu hình Microsoft System Center 2007
summary: >
  Quản lý cấu hình Microsoft System Center 2007 tuân theo chính sách vòng đời [cố định](/lifecycle/policies/fixed) .



  > [!IMPORTANT]

  > Hỗ trợ cho sản phẩm này đã kết thúc. Xem hướng dẫn di chuyển bên dưới.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Service Pack 2
  startDate: 10/22/2009
  endDate: 07/09/2019
- version: Service Pack 1
  startDate: 05/21/2008
  endDate: 01/11/2011
- version: Original Release
  startDate: 11/29/2007
  endDate: 07/14/2009
content: "\n## <a name=\"links\"></a>Liên kết \n* [Hướng dẫn di chuyển](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Thông tin sản phẩm](/mem/configmgr/core/understand/introduction)\n* [Chính sách gói dịch vụ](/lifecycle/policies/fixed#service-packs)"
