### YamlMime:Lifecycle
metadata:
  title: Microsoft ứng dụng ảo hóa lưu trữ 5,1 cho Windows máy tính để bàn
  description: Microsoft ứng dụng ảo hóa lưu trữ 5,1 cho Windows máy tính để bàn tuân theo chính sách vòng đời cố định.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "866204"
name: Microsoft ứng dụng ảo hóa lưu trữ 5,1 cho Windows máy tính để bàn
summary: >+
  Microsoft ứng dụng ảo hóa lưu trữ 5,1 cho Windows máy tính để bàn tuân theo chính sách vòng đời [cố định](/lifecycle/policies/fixed) .


  Điều này áp dụng cho các phiên bản sau: cho máy tính để bàn Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Liên kết \n* [Thông tin sản phẩm](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Phiên bản \n* cho máy tính để bàn Windows"
