### YamlMime:Lifecycle
metadata:
  title: Trình quản lý Cấu hình Microsoft System Center 2012
  description: Trình quản lý Cấu hình Microsoft System Center 2012 tuân theo Chính sách Vòng đời Cố định.
  ms.date: 03/12/2021
  keywords: null
name: Trình quản lý Cấu hình Microsoft System Center 2012
summary: |+
  Trình quản lý Cấu hình Microsoft System Center 2012 tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/fixed).


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>Liên kết 
  * [Chính sách gói dịch vụ](/lifecycle/policies/fixed#service-packs)
  * [System Center Documentation](/system-center/#pivot=components&panel=components-all)
  * [System Center Resources](https://www.microsoft.com/system-center/resources)
  * [Hướng dẫn di chuyển](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)