### YamlMime:Lifecycle
metadata:
  title: Trình bảo mật Máy khách Microsoft Forefront
  description: Trình bảo mật Máy khách Microsoft Forefront tuân theo Chính sách Vòng đời Cố định.
  ms.date: 08/28/2020
name: Trình bảo mật Máy khách Microsoft Forefront
summary: |+
  Trình bảo mật Máy khách Microsoft Forefront tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/fixed).


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Liên kết 
  * [Trình bảo vệ Điểm cuối Hệ thống Trung tâm](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Trình bảo mật Máy khách Forefront đã ngừng hoạt động kể từ ngày 14/7/2015. Các bản cập nhật chống phần mềm có hại và phần mềm gián điệp sẽ không còn khả dụng sau ngày kết thúc hỗ trợ sản phẩm. Vui lòng cân nhắc sử dụng Trình Bảo vệ Điểm cuối Hệ thống Trung tâm như một giải pháp thay thế.