### YamlMime:Lifecycle
metadata:
  title: Trình quản lý Cấu hình Điểm cuối Microsoft
  description: Trình quản lý Cấu hình Điểm cuối Microsoft tuân theo Chính sách Vòng đời Hiện đại.
  ms.date: 01/14/2021
  keywords: SCCM,System Center Configuration Manager
  ms.openlocfilehash: 6ddd93f9daf110d7dd44b2d2e9bb5edc5c20ef37
  ms.sourcegitcommit: 997a0917246bb1fd8acb1cc4477fa5154a5849dd
  ms.translationtype: HT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 01/14/2021
  ms.locfileid: "1378500"
name: Trình quản lý Cấu hình Điểm cuối Microsoft
summary: >
  Trình quản lý Cấu hình Điểm cuối Microsoft tuân theo Chính sách Vòng đời [Cố định](/lifecycle/policies/modern).



  > [!IMPORTANT]

  > Bắt đầu từ phiên bản 1910, Trình quản lý Cấu hình bây giờ là một phần của Trình quản lý Điểm cuối Microsoft.
products:
- m365
policyType: modern-on-prem
supportDates:
  start: 12/08/2015
releases:
- version: Version 2002
  startDate: 04/01/2020
  endDate: 10/01/2021
- version: Version 1910
  startDate: 11/29/2019
  endDate: 05/29/2021
- version: Version 1906
  startDate: 07/26/2019
  endDate: 01/26/2021
- version: Version 1902
  startDate: 03/27/2019
  endDate: 09/27/2020
- version: Version 1810
  startDate: 11/27/2018
  endDate: 12/01/2020
- version: Version 1806
  startDate: 07/31/2018
  endDate: 01/31/2020
- version: Version 1802
  startDate: 03/22/2018
  endDate: 09/22/2019
- version: Version 1710
  startDate: 11/20/2017
  endDate: 05/20/2019
- version: Version 1706
  startDate: 07/31/2017
  endDate: 07/31/2018
- version: Version 1702
  startDate: 03/27/2017
  endDate: 03/27/2018
- version: Version 1610
  startDate: 11/18/2016
  endDate: 11/18/2017
- version: Version 1606 with KB3186654
  startDate: 10/12/2016
  endDate: 10/12/2017
- version: Version 1606
  startDate: 07/22/2016
  endDate: 07/22/2017
- version: Version 1602
  startDate: 03/11/2016
  endDate: 03/11/2016
- version: Version 1511
  startDate: 12/08/2015
  endDate: 12/08/2016
content: "\n## <a name=\"links\"></a>Liên kết \n* [Thông tin dịch vụ](/mem/configmgr/core/servers/manage/current-branch-versions-supported)\n* [Chi tiết Phiên bản](/mem/configmgr/core/servers/manage/updates#version-details)\n* [Trình quản lý Cấu hình Hệ thống Trung tâm hiện là Trình quản lý Cấu hình Điểm cuối Microsoft](/mem/configmgr/core/understand/microsoft-endpoint-manager-faq)\n* [Phiên bản Lịch sử](/mem/configmgr/core/servers/manage/updates#historical-versions)\n* [Trình quản lý Cấu hình là gì](/mem/configmgr/core/understand/introduction)"
