### YamlMime:Lifecycle
metadata:
  title: Ứng dụng PixelSense Suite 1,0
  description: Ứng dụng PixelSense Suite 1,0 tuân theo chính sách vòng đời cố định.
  ms.date: 07/28/2020
  ms.openlocfilehash: 5359b0dd917124f3b47cb74f30a3ff92657c2155
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: vi-VN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "846905"
name: Ứng dụng PixelSense Suite 1,0
summary: >+
  Ứng dụng PixelSense Suite 1,0 tuân theo chính sách vòng đời [cố định](/lifecycle/policies/fixed) .


products:
- windows
policyType: fixed
supportDates:
  start: 01/01/2009
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 1
  startDate: 08/09/2009
  endDate: 01/08/2019
- version: Original Release
  startDate: 01/01/2009
  endDate: 01/14/2014
content: ''
